package Ui.GuiPackageEvent.GuiPackageFormulariosEvent;

import DTOS.EventDTO;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.StyleContext;
import java.util.List;
import java.awt.*;
import java.util.Locale;

public class CalendarView {
    private JPanel PanelPrincipalClanderEvents;
    private JPanel Paneltitulo;
    private JPanel panelPrincipalTabla;
    private JTable tableeventos;

    // Cambiar CalendarEvents a clase estática para evitar dependencias de instancia
    public static class CalendarEvents {
        private JPanel panelPrincipalClanderEvents;
        private JTable tablaEventos;
        private DefaultTableModel tablaEventosModelo;

        public CalendarEvents() {

            // NO crear aquí nuevas instancias de CalendarView ni CalendarEvents
            tablaEventosModelo = new DefaultTableModel(new String[]{"ID", "Nombre", "Fecha"}, 0);
            tablaEventos = new JTable(tablaEventosModelo);

            JScrollPane scrollPane = new JScrollPane(tablaEventos);
            panelPrincipalClanderEvents = new JPanel(new BorderLayout());
            panelPrincipalClanderEvents.add(scrollPane, BorderLayout.CENTER);
        }

        public void cargarEventosEnCalendario(List<EventDTO> eventos) {
            if (tablaEventosModelo == null) {
                System.err.println("Error: tablaEventosModelo no ha sido inicializado.");
                return;
            }

            tablaEventosModelo.setRowCount(0); // limpia tabla

            for (EventDTO evento : eventos) {
                Object[] fila = {
                        evento.getEventId(),
                        evento.getEventName(),
                        evento.getStartDate()
                };
                tablaEventosModelo.addRow(fila);
            }
        }

        public JPanel getPanelPrincipalClanderEvents() {
            return panelPrincipalClanderEvents;
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    private void $$$setupUI$$$() {
        PanelPrincipalClanderEvents = new JPanel();
        PanelPrincipalClanderEvents.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setBackground(new Color(-15591660));
        PanelPrincipalClanderEvents.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER,
                GridConstraints.FILL_BOTH,
                GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                null, null, null, 0, false));
        Paneltitulo = new JPanel();
        Paneltitulo.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        Paneltitulo.setBackground(new Color(-15591660));
        Paneltitulo.setEnabled(false);
        panel1.add(Paneltitulo, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER,
                GridConstraints.FILL_BOTH,
                GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$(null, -1, 22, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setForeground(new Color(-330753));
        label1.setText("Calendar View");
        Paneltitulo.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER,
                GridConstraints.FILL_NONE,
                GridConstraints.SIZEPOLICY_FIXED,
                GridConstraints.SIZEPOLICY_FIXED,
                null, null, null, 0, false));
        panelPrincipalTabla = new JPanel();
        panelPrincipalTabla.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panelPrincipalTabla.setBackground(new Color(-15591660));
        panel1.add(panelPrincipalTabla, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER,
                GridConstraints.FILL_BOTH,
                GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                null, null, null, 0, false));
        tableeventos = new JTable();
        tableeventos.setBackground(new Color(-15591660));
        panelPrincipalTabla.add(tableeventos, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER,
                GridConstraints.FILL_BOTH,
                GridConstraints.SIZEPOLICY_WANT_GROW,
                GridConstraints.SIZEPOLICY_WANT_GROW,
                null, new Dimension(150, 50), null, 0, false));
    }

    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(),
                size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ?
                new Font(font.getFamily(), font.getStyle(), font.getSize()) :
                new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    public JComponent $$$getRootComponent$$$() {
        return PanelPrincipalClanderEvents;
    }

    public JPanel getPanelPrincipalClanderEvents() {
        return PanelPrincipalClanderEvents;
    }

    public JPanel getPaneltitulo() {
        return Paneltitulo;
    }

    public JPanel getPanelPrincipalTabla() {
        return panelPrincipalTabla;
    }

    public JTable getTableeventos() {
        return tableeventos;
    }
}
