package Ui.GuiPackageEvent.GuiPackageFormulariosEvent;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;

import DTOS.EventDTO;
import Repository.EventRepository;


import java.time.*;
import java.time.format.DateTimeFormatter;
import java.time.format.TextStyle;
import java.util.*;
import java.util.List;

public class CalendarEvents extends JFrame {
    private JPanel PanelPrincipalClanderEvents;
    private JComboBox comboBoxmonhts;
    private JComboBox comboBoxyears;
    private JButton showEventsButton;
    private JPanel Paneltitulo;
    private JPanel panelcomboboxs;
    private JPanel CalendarPanel;
    private JTabbedPane tabbedPane1;
    private JComboBox<String> monthCombo;
    private JComboBox<Integer> yearCombo;
    private EventRepository repository;
    private List<EventDTO> eventos;


    public void drawCalendar(int year, int month) {
        CalendarPanel.removeAll();

        // Días de la semana
        String[] dayNames = {"Dom", "Lun", "Mar", "Mié", "Jue", "Vie", "Sáb"};
        for (String day : dayNames) {
            JLabel label = new JLabel(day, SwingConstants.CENTER);
            label.setFont(new Font("Arial", Font.BOLD, 14));
            CalendarPanel.add(label);
        }

        // Información del mes
        YearMonth yearMonth = YearMonth.of(year, month);
        int totalDays = yearMonth.lengthOfMonth();
        int startDayOfWeek = yearMonth.atDay(1).getDayOfWeek().getValue(); // Lunes = 1, Domingo = 7

        int emptyCells = startDayOfWeek % 7;

        // Celdas vacías antes del día 1
        for (int i = 0; i < emptyCells; i++) {
            CalendarPanel.add(new JLabel(""));
        }

        // Botones para cada día
        for (int day = 1; day <= totalDays; day++) {
            JButton btn = new JButton(String.valueOf(day));
            btn.setBackground(Color.WHITE);
            btn.addActionListener(e -> {
                JOptionPane.showMessageDialog(null, "Día seleccionado: " + btn.getText());
            });
            CalendarPanel.add(btn);
        }
        // Botones para cada día del mes
        for (int day = 1; day <= totalDays; day++) {
            JButton btn = new JButton(String.valueOf(day)); // Botón con el número del día
            btn.setBackground(new Color(-14829228)); // Color de fondo del botón
            btn.setFocusPainted(false);

            // Formato de la fecha actual: YYYY-MM-DD
            String fechaActual = String.format("%04d-%02d-%02d", year, month, day);

            // Verificar si hay eventos en esta fecha
            for (EventDTO ev : eventos) {
                if (ev.getStartDate().equals(fechaActual)) {
                    btn.setBackground(Color.CYAN); // Colorea el botón si hay un evento ese día
                    btn.setToolTipText(ev.getEventName()); // Muestra el nombre del evento al pasar el mouse
                    break;
                }
            }

            // Acción al hacer clic en el botón del día
            btn.addActionListener(e -> {
                JOptionPane.showMessageDialog(null, "Día seleccionado: " + btn.getText());
            });

            // Añadir botón al panel del calendario
            CalendarPanel.add(btn);
        }

        CalendarPanel.revalidate();
        CalendarPanel.repaint();

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        PanelPrincipalClanderEvents = new JPanel();
        PanelPrincipalClanderEvents.setLayout(new GridLayoutManager(4, 1, new Insets(0, 0, 0, 0), -1, -1));
        PanelPrincipalClanderEvents.setBackground(new Color(-15591660));
        Paneltitulo = new JPanel();
        Paneltitulo.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        Paneltitulo.setBackground(new Color(-15591660));
        Paneltitulo.setEnabled(false);
        PanelPrincipalClanderEvents.add(Paneltitulo, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$(null, -1, 22, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setForeground(new Color(-330753));
        label1.setText("Calendar View");
        Paneltitulo.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        panelcomboboxs = new JPanel();
        panelcomboboxs.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panelcomboboxs.setBackground(new Color(-15591660));
        PanelPrincipalClanderEvents.add(panelcomboboxs, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        comboBoxmonhts = new JComboBox();
        comboBoxmonhts.setBackground(new Color(-15591660));
        comboBoxmonhts.setEditable(false);
        comboBoxmonhts.setEnabled(true);
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        comboBoxmonhts.setModel(defaultComboBoxModel1);
        panelcomboboxs.add(comboBoxmonhts, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(74, 57), null, 0, false));
        comboBoxyears = new JComboBox();
        comboBoxyears.setBackground(new Color(-15591660));
        comboBoxyears.setEditable(false);
        comboBoxyears.setEnabled(true);
        panelcomboboxs.add(comboBoxyears, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(74, 57), null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        PanelPrincipalClanderEvents.add(panel1, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        CalendarPanel = new JPanel();
        CalendarPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        CalendarPanel.setBackground(new Color(-15591660));
        panel1.add(CalendarPanel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        tabbedPane1 = new JTabbedPane();
        CalendarPanel.add(tabbedPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        showEventsButton = new JButton();
        showEventsButton.setBackground(new Color(-14829228));
        showEventsButton.setForeground(new Color(-330753));
        showEventsButton.setText("Show Events");
        PanelPrincipalClanderEvents.add(showEventsButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return PanelPrincipalClanderEvents;
    }

    /**
     * @noinspection ALL
     */
    public JPanel getPanelPrincipalClanderEvents() {
        return PanelPrincipalClanderEvents;
    }
}
