package Ui.GuiPackageFinancilas;

import DTOS.EventDTO;
import Ui.GuiPackageFinancilas.GuiPackageFormilarioFinancial.GuiFormularioFinancials;
import Ui.GuiPackageMainMenu.GuiMainMenu;
import Services.FinanceService;
import Repository.FinancialRepository;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.math.BigDecimal;
import java.util.Locale;

public class GuiFinancials {
    private JPanel panelPrincipalFinancials;
    private JPanel panelTituloPrincipal;
    private JLabel eventMasterProMenuLabel;
    private JPanel PanelMenuFinancials;
    private JButton exitButton;
    private JButton backToMainMenuButton;
    private JButton viewFinancialSummaryButton;
    private JButton viewExpensesButton;
    private JButton viewIncomeButton;
    private JButton registerBudgetButton;
    private JButton viewFinancialsButton;
    private JButton trackIncomeButton;
    private JButton trackExpenseButton;
    private GuiFormularioFinancials guiFormularioFinancials;
    private FinanceService financeService;
    private FinancialRepository financialRepository;


    public GuiFinancials() {


        financialRepository = new FinancialRepository();
        financeService = new FinanceService();
        // Botón para regresar al menú principal
        backToMainMenuButton.addActionListener(e -> {
            JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(panelPrincipalFinancials);
            currentFrame.dispose();

            GuiMainMenu guiMainMenu = new GuiMainMenu();
            JFrame frame = new JFrame("Main Menu");
            frame.setContentPane(guiMainMenu.getPanelPrincipalMainMenu());
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        });

        // Botón para salir de la aplicación
        exitButton.addActionListener(e -> {
            JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(panelPrincipalFinancials);
            currentFrame.dispose();

            JOptionPane.showMessageDialog(null, "Thank you for using Event Master Pro!", "Exit", JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        });

        // Botón para registrar presupuesto
        registerBudgetButton.addActionListener(e -> {
            try {
                JFrame frame = new JFrame("Registrar Budget");

                // Ocultar componentes innecesarios en formulario financiero
                guiFormularioFinancials.getViewFinancialsSumary().setVisible(false);
                guiFormularioFinancials.getButtonViewFinancials().setVisible(false);
                guiFormularioFinancials.getLabelViewFinancials().setVisible(false);
                guiFormularioFinancials.getLabelViewFinancilaSummry().setVisible(false);

                frame.setContentPane(guiFormularioFinancials.getPanelPrincipalFormularioFinancials());
                frame.setSize(900, 600);
                frame.setResizable(false);
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);

                EventDTO selectedEvent = (EventDTO) guiFormularioFinancials.getComboBoxListEVent().getSelectedItem();
                if (selectedEvent == null) {
                    JOptionPane.showMessageDialog(null, "Debes seleccionar un evento.");
                    return;
                }

                String montoTexto = guiFormularioFinancials.getTextFieldBudget().getText().trim();
                if (montoTexto.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Debes ingresar un monto.");
                    return;
                }

                BigDecimal budget = new BigDecimal(montoTexto);
                String eventId = selectedEvent.getEventId();

                boolean registrado = financeService.registerFinancials(eventId, budget, null, null);

                if (registrado) {
                    JOptionPane.showMessageDialog(null, "Presupuesto registrado para: " + selectedEvent.getEventName());
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Monto inválido. Introduce un número válido.");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
                ex.printStackTrace();
            }
        });

        // Botón para visualizar finanzas (abre formulario)

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panelPrincipalFinancials = new JPanel();
        panelPrincipalFinancials.setLayout(new GridLayoutManager(2, 3, new Insets(0, 0, 0, 0), -1, -1));
        panelPrincipalFinancials.setBackground(new Color(-15591660));
        panel1.add(panelPrincipalFinancials, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panelTituloPrincipal = new JPanel();
        panelTituloPrincipal.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        panelTituloPrincipal.setBackground(new Color(-15591660));
        panelPrincipalFinancials.add(panelTituloPrincipal, new GridConstraints(0, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        eventMasterProMenuLabel = new JLabel();
        Font eventMasterProMenuLabelFont = this.$$$getFont$$$("Roboto Light", Font.BOLD, 28, eventMasterProMenuLabel.getFont());
        if (eventMasterProMenuLabelFont != null) eventMasterProMenuLabel.setFont(eventMasterProMenuLabelFont);
        eventMasterProMenuLabel.setForeground(new Color(-330753));
        eventMasterProMenuLabel.setText("Event Master Pro ");
        panelTituloPrincipal.add(eventMasterProMenuLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panelTituloPrincipal.add(spacer1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        panelTituloPrincipal.add(spacer2, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        panelTituloPrincipal = new JPanel();
        panelTituloPrincipal.setLayout(new GridLayoutManager(8, 1, new Insets(0, 0, 0, 0), -1, -1));
        panelTituloPrincipal.setBackground(new Color(-15591660));
        panelPrincipalFinancials.add(panelTituloPrincipal, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(207, 298), null, 0, false));
        exitButton = new JButton();
        exitButton.setBackground(new Color(-14829228));
        exitButton.setEnabled(true);
        exitButton.setForeground(new Color(-330753));
        exitButton.setText("Exit");
        panelTituloPrincipal.add(exitButton, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        backToMainMenuButton = new JButton();
        backToMainMenuButton.setBackground(new Color(-14829228));
        backToMainMenuButton.setEnabled(true);
        backToMainMenuButton.setForeground(new Color(-330753));
        backToMainMenuButton.setText("Back to Main Menu");
        panelTituloPrincipal.add(backToMainMenuButton, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        viewFinancialSummaryButton = new JButton();
        viewFinancialSummaryButton.setBackground(new Color(-14829228));
        viewFinancialSummaryButton.setEnabled(true);
        viewFinancialSummaryButton.setForeground(new Color(-330753));
        viewFinancialSummaryButton.setText("View Financial Summary");
        panelTituloPrincipal.add(viewFinancialSummaryButton, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer3 = new Spacer();
        panelTituloPrincipal.add(spacer3, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer4 = new Spacer();
        panelTituloPrincipal.add(spacer4, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        registerBudgetButton = new JButton();
        registerBudgetButton.setBackground(new Color(-14829228));
        registerBudgetButton.setEnabled(true);
        registerBudgetButton.setForeground(new Color(-330753));
        registerBudgetButton.setText("register Budget");
        panelTituloPrincipal.add(registerBudgetButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer5 = new Spacer();
        panelTituloPrincipal.add(spacer5, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        viewFinancialsButton = new JButton();
        viewFinancialsButton.setBackground(new Color(-14829228));
        viewFinancialsButton.setEnabled(true);
        viewFinancialsButton.setForeground(new Color(-330753));
        viewFinancialsButton.setText("View Financials ");
        panelTituloPrincipal.add(viewFinancialsButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        panel2.setBackground(new Color(-15591660));
        panelPrincipalFinancials.add(panel2, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setBackground(new Color(-15591660));
        label1.setEnabled(true);
        Font label1Font = this.$$$getFont$$$(null, -1, 72, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setForeground(new Color(-330753));
        label1.setText("Welcome To Manage Financials");
        panel2.add(label1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer6 = new Spacer();
        panel2.add(spacer6, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer7 = new Spacer();
        panel2.add(spacer7, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    public JPanel getPanelPrincipalFinancials() {
        return panelPrincipalFinancials;
    }
}
