package Ui.GuiPackageMainMenu;

import Ui.GuiPackageAccessControl.GuiAccessControl;
import Ui.GuiPackageArtist.GuiArtist;
import Ui.GuiPackageEvent.GuiEvent;
import Ui.GuiPackageFinancilas.GuiFInancials;
import Ui.GuiPackageTicket.GuiTicket;
import Ui.GuiPackageVenue.GuiVenue;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Locale;

public class GuiMainMenu {
    private JPanel PanelPrincipalMainMenu;
    private JPanel JpanelTituloPrincipal;
    private JLabel eventMasterProMenuLabel;
    private JPanel JPanelMenu;
    private JButton exitButton;
    private JButton manageAccessControlButton;
    private JButton manageTicketButton;
    private JButton manageFinancialsButton;
    private JButton manageVenueButton;
    private JButton manageArtistButton;
    private JButton manageEventButton;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    public GuiMainMenu() {
        manageEventButton.addActionListener(new ActionListener() {

            @Override
           public void actionPerformed(ActionEvent e) {
               JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(PanelPrincipalMainMenu);
                currentFrame.dispose(); // Cierra la ventana actual

                GuiEvent guiEvent = new GuiEvent();
                JFrame frame = new JFrame("Manage Event");
                frame.setContentPane(guiEvent.getPanelPrincipalEvent());
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
                frame.setVisible(true);

            }
           });
        manageArtistButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(PanelPrincipalMainMenu);
                currentFrame.dispose(); // Cierra la ventana actual

                GuiArtist guiArtist = new GuiArtist();
                JFrame frame = new JFrame("Manage Artist");
                frame.setContentPane(guiArtist.getPanelPrincipalArtist());
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
                frame.setVisible(true);

            }
        });
        manageVenueButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(PanelPrincipalMainMenu);
                currentFrame.dispose(); // Cierra la ventana actual

                GuiVenue guiVenue = new GuiVenue();
                JFrame frame = new JFrame("Manage Venue");
                frame.setContentPane(guiVenue.getPanelPrincipalVenue());
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
                frame.setVisible(true);

            }
        });
        manageFinancialsButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(PanelPrincipalMainMenu);
                currentFrame.dispose(); // Cierra la ventana actual

                GuiFInancials guiFInancials = new GuiFInancials();
                JFrame frame = new JFrame("Manage Financials");
                frame.setContentPane(guiFInancials.getPanelPrincipalFinancials());
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
                frame.setVisible(true);

            }
        });
        manageTicketButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(PanelPrincipalMainMenu);
                currentFrame.dispose(); // Cierra la ventana actual

                GuiTicket guiTicket = new GuiTicket();
                JFrame frame = new JFrame("Manage Ticket");
                frame.setContentPane(guiTicket.getPanelPrincipalTicket());
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
                frame.setVisible(true);

            }
        });
        manageAccessControlButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(PanelPrincipalMainMenu);
                currentFrame.dispose(); // Cierra la ventana actual

                GuiAccessControl guiAccessControl = new GuiAccessControl();
                JFrame frame = new JFrame("Manage Access Control");
                frame.setContentPane(guiAccessControl.getPanelPrincipalAccessControl());
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
                frame.setVisible(true);

            }
        });
        exitButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(PanelPrincipalMainMenu);
                currentFrame.dispose(); // Cierra la ventana actual

                JFrame frame = new JFrame("Exit");
                JOptionPane.showMessageDialog(frame, "Thank you for using Event Master Pro!", "Exit", JOptionPane.INFORMATION_MESSAGE);
                System.exit(0); // Cierra la aplicación

            }
        });
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        PanelPrincipalMainMenu = new JPanel();
        PanelPrincipalMainMenu.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        PanelPrincipalMainMenu.setBackground(new Color(-15591660));
        panel1.add(PanelPrincipalMainMenu, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        JpanelTituloPrincipal = new JPanel();
        JpanelTituloPrincipal.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        JpanelTituloPrincipal.setBackground(new Color(-15591660));
        PanelPrincipalMainMenu.add(JpanelTituloPrincipal, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        eventMasterProMenuLabel = new JLabel();
        Font eventMasterProMenuLabelFont = this.$$$getFont$$$("Roboto Light", Font.BOLD, 28, eventMasterProMenuLabel.getFont());
        if (eventMasterProMenuLabelFont != null) eventMasterProMenuLabel.setFont(eventMasterProMenuLabelFont);
        eventMasterProMenuLabel.setForeground(new Color(-330753));
        eventMasterProMenuLabel.setText("Event Master Pro ");
        JpanelTituloPrincipal.add(eventMasterProMenuLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        JpanelTituloPrincipal.add(spacer1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        JPanelMenu = new JPanel();
        JPanelMenu.setLayout(new GridLayoutManager(10, 1, new Insets(0, 0, 0, 0), -1, -1));
        JPanelMenu.setBackground(new Color(-15591660));
        PanelPrincipalMainMenu.add(JPanelMenu, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(207, 298), null, 0, false));
        exitButton = new JButton();
        exitButton.setBackground(new Color(-14829228));
        exitButton.setEnabled(true);
        exitButton.setForeground(new Color(-330753));
        exitButton.setText("Exit");
        JPanelMenu.add(exitButton, new GridConstraints(8, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        manageAccessControlButton = new JButton();
        manageAccessControlButton.setBackground(new Color(-14829228));
        manageAccessControlButton.setEnabled(true);
        manageAccessControlButton.setForeground(new Color(-330753));
        manageAccessControlButton.setText("Manage Access Control");
        JPanelMenu.add(manageAccessControlButton, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        manageTicketButton = new JButton();
        manageTicketButton.setBackground(new Color(-14829228));
        manageTicketButton.setEnabled(true);
        manageTicketButton.setForeground(new Color(-330753));
        manageTicketButton.setText("Manage Ticket");
        JPanelMenu.add(manageTicketButton, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        manageFinancialsButton = new JButton();
        manageFinancialsButton.setBackground(new Color(-14829228));
        manageFinancialsButton.setEnabled(true);
        manageFinancialsButton.setForeground(new Color(-330753));
        manageFinancialsButton.setText("Manage Financials");
        JPanelMenu.add(manageFinancialsButton, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        manageVenueButton = new JButton();
        manageVenueButton.setBackground(new Color(-14829228));
        manageVenueButton.setEnabled(true);
        manageVenueButton.setForeground(new Color(-330753));
        manageVenueButton.setText("Manage Venue");
        JPanelMenu.add(manageVenueButton, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        manageArtistButton = new JButton();
        manageArtistButton.setBackground(new Color(-14829228));
        manageArtistButton.setEnabled(true);
        manageArtistButton.setForeground(new Color(-330753));
        manageArtistButton.setText("Manage Artist");
        JPanelMenu.add(manageArtistButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        manageEventButton = new JButton();
        manageEventButton.setBackground(new Color(-14829228));
        manageEventButton.setEnabled(true);
        manageEventButton.setForeground(new Color(-330753));
        manageEventButton.setText("Manage Event");
        JPanelMenu.add(manageEventButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        JPanelMenu.add(spacer2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer3 = new Spacer();
        JPanelMenu.add(spacer3, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer4 = new Spacer();
        JPanelMenu.add(spacer4, new GridConstraints(9, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        panel2.setBackground(new Color(-15591660));
        PanelPrincipalMainMenu.add(panel2, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setBackground(new Color(-15591660));
        label1.setEnabled(true);
        Font label1Font = this.$$$getFont$$$(null, -1, 72, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setForeground(new Color(-330753));
        label1.setText("Welcome To Event Master Pro");
        panel2.add(label1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer5 = new Spacer();
        panel2.add(spacer5, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer6 = new Spacer();
        panel2.add(spacer6, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    public JPanel getPanelPrincipalMainMenu() {
        return PanelPrincipalMainMenu;
    }
}
