package Ui.GuiPackageTicket.GuiPackageFormularioTicket;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Locale;

public class GuiFormularioTicket {
    private JPanel PanelFolmularioCreateTicketType;
    private JTextField FIeldCodeTicket;
    private JPanel PanelIDEvent;
    private JTextField FieldPrecioTicket;
    private JPanel PanelEventName;
    private JPanel PanelComboboxTypeTicket;
    private JComboBox comboBoxTicketT;
    private JPanel PanelEvent;
    private JButton createTicketButton;
    private JButton buttonRegistreSale;
    private JPanel PanelTituloPrincipal;
    private JLabel LabelTituloPrincipal;
    private JPanel PanelCodeTicket;
    private JTextField textField1;
    private JTextField textFieldEstadoDeUso;
    private JTextField textFieldEstadoDeVenta;
    private JTextField textFieldEventName;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    public GuiFormularioTicket() {
        buttonRegistreSale.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        PanelFolmularioCreateTicketType = new JPanel();
        PanelFolmularioCreateTicketType.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(13, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setBackground(new Color(-15591660));
        panel1.setForeground(new Color(-330753));
        PanelFolmularioCreateTicketType.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        PanelCodeTicket = new JPanel();
        PanelCodeTicket.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        PanelCodeTicket.setBackground(new Color(-15591660));
        PanelCodeTicket.setEnabled(false);
        Font PanelCodeTicketFont = this.$$$getFont$$$(null, -1, 22, PanelCodeTicket.getFont());
        if (PanelCodeTicketFont != null) PanelCodeTicket.setFont(PanelCodeTicketFont);
        PanelCodeTicket.setForeground(new Color(-330753));
        panel1.add(PanelCodeTicket, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        PanelCodeTicket.setBorder(BorderFactory.createTitledBorder(null, "Code Ticket", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        FIeldCodeTicket = new JTextField();
        FIeldCodeTicket.setBackground(new Color(-330753));
        FIeldCodeTicket.setForeground(new Color(-16777216));
        FIeldCodeTicket.setText("");
        PanelCodeTicket.add(FIeldCodeTicket, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        PanelIDEvent = new JPanel();
        PanelIDEvent.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        PanelIDEvent.setBackground(new Color(-15591660));
        PanelIDEvent.setEnabled(false);
        PanelIDEvent.setForeground(new Color(-330753));
        panel1.add(PanelIDEvent, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        PanelIDEvent.setBorder(BorderFactory.createTitledBorder(null, "Price Ticket", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        FieldPrecioTicket = new JTextField();
        FieldPrecioTicket.setEditable(false);
        FieldPrecioTicket.setEnabled(true);
        PanelIDEvent.add(FieldPrecioTicket, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        PanelEventName = new JPanel();
        PanelEventName.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        PanelEventName.setBackground(new Color(-15591660));
        PanelEventName.setEnabled(false);
        PanelEventName.setForeground(new Color(-330753));
        panel1.add(PanelEventName, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        PanelEventName.setBorder(BorderFactory.createTitledBorder(null, "Estado de venta", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        textFieldEstadoDeVenta = new JTextField();
        PanelEventName.add(textFieldEstadoDeVenta, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        PanelEvent = new JPanel();
        PanelEvent.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        PanelEvent.setBackground(new Color(-15591660));
        PanelEvent.setEnabled(false);
        PanelEvent.setForeground(new Color(-330753));
        panel1.add(PanelEvent, new GridConstraints(10, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        PanelEvent.setBorder(BorderFactory.createTitledBorder(null, "Event", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        textFieldEventName = new JTextField();
        PanelEvent.add(textFieldEventName, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel2.setBackground(new Color(-15591660));
        panel1.add(panel2, new GridConstraints(12, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        createTicketButton = new JButton();
        createTicketButton.setBackground(new Color(-14829228));
        createTicketButton.setForeground(new Color(-16777216));
        createTicketButton.setText("Create Ticket");
        panel2.add(createTicketButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        buttonRegistreSale = new JButton();
        buttonRegistreSale.setBackground(new Color(-14829228));
        buttonRegistreSale.setForeground(new Color(-16777216));
        buttonRegistreSale.setText("Registre Sale");
        panel2.add(buttonRegistreSale, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(11, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        panel1.add(spacer2, new GridConstraints(9, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer3 = new Spacer();
        panel1.add(spacer3, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer4 = new Spacer();
        panel1.add(spacer4, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer5 = new Spacer();
        panel1.add(spacer5, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        PanelTituloPrincipal = new JPanel();
        PanelTituloPrincipal.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        PanelTituloPrincipal.setBackground(new Color(-15591660));
        panel1.add(PanelTituloPrincipal, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        LabelTituloPrincipal = new JLabel();
        Font LabelTituloPrincipalFont = this.$$$getFont$$$(null, -1, 36, LabelTituloPrincipal.getFont());
        if (LabelTituloPrincipalFont != null) LabelTituloPrincipal.setFont(LabelTituloPrincipalFont);
        LabelTituloPrincipal.setForeground(new Color(-330753));
        LabelTituloPrincipal.setText("");
        PanelTituloPrincipal.add(LabelTituloPrincipal, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        PanelComboboxTypeTicket = new JPanel();
        PanelComboboxTypeTicket.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        PanelComboboxTypeTicket.setBackground(new Color(-15591660));
        PanelComboboxTypeTicket.setEnabled(false);
        PanelComboboxTypeTicket.setForeground(new Color(-330753));
        panel1.add(PanelComboboxTypeTicket, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        PanelComboboxTypeTicket.setBorder(BorderFactory.createTitledBorder(null, "Ticket Type", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        comboBoxTicketT = new JComboBox();
        comboBoxTicketT.setBackground(new Color(-330753));
        comboBoxTicketT.setForeground(new Color(-16777216));
        PanelComboboxTypeTicket.add(comboBoxTicketT, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel3.setBackground(new Color(-15591660));
        panel3.setEnabled(false);
        panel3.setForeground(new Color(-330753));
        panel1.add(panel3, new GridConstraints(8, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panel3.setBorder(BorderFactory.createTitledBorder(null, "Estado de uso", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        textFieldEstadoDeUso = new JTextField();
        panel3.add(textFieldEstadoDeUso, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return PanelFolmularioCreateTicketType;
    }

    public JPanel getPanelFolmularioCreateTicketType() {
        return PanelFolmularioCreateTicketType;
    }

    public JTextField getFIeldCodeTicket() {
        return FIeldCodeTicket;
    }

    public JPanel getPanelIDEvent() {
        return PanelIDEvent;
    }

    public JTextField getFieldPrecioTicket() {
        return FieldPrecioTicket;
    }

    public JPanel getPanelComboboxTypeTicket() {
        return PanelComboboxTypeTicket;
    }

    public JPanel getPanelEventName() {
        return PanelEventName;
    }

    public JComboBox getComboBoxTicketT() {
        return comboBoxTicketT;
    }

    public JPanel getPanelEvent() {
        return PanelEvent;
    }

    public JButton getCreateTicketButton() {
        return createTicketButton;
    }

    public JButton getButtonRegistreSale() {
        return buttonRegistreSale;
    }

    public JPanel getPanelTituloPrincipal() {
        return PanelTituloPrincipal;
    }

    public JLabel getLabelTituloPrincipal() {
        return LabelTituloPrincipal;
    }

    public JPanel getPanelCodeTicket() {
        return PanelCodeTicket;
    }

    public JTextField getTextField1() {
        return textField1;
    }

    public JTextField getTextFieldEstadoDeUso() {
        return textFieldEstadoDeUso;
    }

    public JTextField getTextFieldEstadoDeVenta() {
        return textFieldEstadoDeVenta;
    }
}
